# Basic NePS Configuration Example
pipeline_space:
  learning_rate:
    lower: 1e-5
    upper: 1e-1
    log: true  # Log scale for learning rate
  epochs:
    lower: 5
    upper: 20
    is_fidelity: true
  optimizer:
    choices: [adam, sgd, adamw]
  batch_size: 64

root_directory: path/to/results       # Directory for result storage
max_evaluations_total: 20             # Budget
