# -*- coding: utf-8 -*-
"""NePS_Tutorial_NextAI25_with_MO_priors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FRM4m0tWWgH3xTJTU5_DWlO3o6n1GI_5

# Using NePS for Hyperparameter Optimization
"""

# Commented out IPython magic to ensure Python compatibility.
# # @title Installations and restarting of the runtime
# %%capture
# !git clone --single-branch --branch soham https://github.com/automl/neps_colab_playground.git
# !cd neps_colab_playground && pip install -r requirements.txt --quiet
# 
# !pip install yahpo-gym
# !pip install ConfigSpace==0.4.21  # important to overwrite after installing NePS
# 
# !pip install --force-reinstall --no-deps git+https://github.com/automl/neps.git@mo-txt-files-fidelity-stopping-crit

# Colab requires restarting of the runtime after more complex installations.
# This will also terminate a "run all".
import os
os.kill(os.getpid(), 9)

# Commented out IPython magic to ensure Python compatibility.
# # @title Setup
# %%capture
# 
# import neps
# 
# from IPython.display import Image
# from functools import partial
# import logging
# from matplotlib import pyplot as plt
# import numpy as np
# import time
# import warnings
# 
# warnings.filterwarnings("ignore", category=DeprecationWarning)
# warnings.filterwarnings("ignore", category=FutureWarning)
# warnings.filterwarnings("ignore", category=UserWarning)
# logging.getLogger("neps.plot.tensorboard_eval").setLevel(logging.ERROR)

# Commented out IPython magic to ensure Python compatibility.
# Set working directory and check task repository
# %cd neps_colab_playground/
# %ls

"""## Quick Start: synthetic trials

Using a synthetic function for black-box optimization.
"""

import math

# The task: treat Branin input as hyperparameters optimized by NePS
def branin(x1, x2):
  """ The 2-dimensional Branin function.

  https://www.sfu.ca/~ssurjano/branin.html
  """
  a = 1
  b = 5.1 / (4 * math.pi**2)
  c = 5 / math.pi
  r = 6
  s = 10
  t = 1 / 8 * math.pi

  f = a * (x2 - b * x1**2 + c * x1 - r) ** 2 + s * (1 - t) * math.cos(x1) + s
  return f

# The search space
pipeline_space = dict(
    x1=neps.Float(lower=-5, upper=10),
    x2=neps.Float(lower=0, upper=15)
)

# The optimization
neps.run(
    evaluate_pipeline=branin,
    pipeline_space=pipeline_space,
    root_directory="branin_demo/",
    evaluations_to_spend=10,
)

!cat branin_demo/summary/best_config.txt

"""## The DL task

Multi-class classification using simple CNNs.

We prepared a standard loop that will train and evaluate a model on MNIST given hyperparameters for the architecture and training pipeline.
"""

# Commented out IPython magic to ensure Python compatibility.
# # @title Download dataset
# %%capture
# from utils import prepare_mnist_dataloader
# 
# _, _, _, _ = prepare_mnist_dataloader()

"""

To view the full training code visit [here](https://github.com/automl/neps_tutorial_DL2024/blob/main/train.py).

To edit the training code directly in Colab, navigate to `model.py` on the file explorer in Colab (on the left), edit the file, `Runtime -> Restart session` and re-execute the relevant cells."""

from train import training_pipeline
from tutorials.utils import set_seeds

# Test the pipeline on a subsampled dataset for a few epochs
training_pipeline(
    # checkpoint controller
    out_dir=None,
    load_dir=None,
    # possible hyperparameters
    num_layers=1,
    batch_size=512,
    # possible fidelities
    subsample=0.1,
    epochs=2,
    # other control variables
    val_fraction = 0.3,
    allow_checkpointing = False,
    verbose=True,
)

"""Here, the `objective_to_minimize` is equivalent to `1 - val_accuracy` or _validation error_ as NePS needs a minimizing metric.

For a more detailed look into the pipeline, see [github.com/automl/neps_colab_playground](https://github.com/automl/neps_colab_playground).

## Running a basic HPO

Given that our standard training pipeline works, we can use NePS to easily tune its hyperparameters with minimal code changes.

Using NePS always follows the same pattern:

1. Define a `evaluate_pipeline` function capable of evaluating different hyperparameter settings for your problem

2. Define a search space named `pipeline_space` of those parameters

3. Call `neps.run` to optimize `evaluate_pipeline` over `pipeline_space`


For more details, see [neps.run](https://automl.github.io/neps/latest/reference/neps_run/?h=run), the [API reference](https://automl.github.io/neps/latest/api/neps/api/), or the [documentation](https://automl.github.io/neps/latest/reference/neps_run/).
"""

# 1. Creating a NePS wrapper for our DL task
def evaluate_pipeline(
    pipeline_directory,  # For saving checkpoints
    previous_pipeline_directory,  # For loading checkpoints
    **hyperparameters,  # Determined by HPO algorithms and passed by NePS
):
    return training_pipeline(
        **hyperparameters,
        out_dir=pipeline_directory,
        load_dir=previous_pipeline_directory,
        # misc settings
        batch_size=512,
        log_neps_tensorboard=True,
        verbose=False,
        allow_checkpointing=True,
        use_for_demo=True  # toggle as desired
    )

# 2. Creating the search space, tuning only the learning rate for now
pipeline_space = dict(
    learning_rate=neps.Float(1e-6, 1e-1, log=True),
)

# 3. NePS optimization call
logging.basicConfig(level=logging.INFO, force=True)
set_seeds(1)
neps.run(
    evaluate_pipeline=evaluate_pipeline,
    root_directory="results_hpo_demo",
    pipeline_space=pipeline_space,
    evaluations_to_spend=3  # HPO budget
)

"""### Analysing the run

To check the status of runs at anytime from the command line:
"""

!python -m neps.status results_hpo_demo/  # the output directory as argument

"""The output directory is structured in the following manner where `configs/` contain the individual configurations sampled and their performance.


"""

# Commented out IPython magic to ensure Python compatibility.
# %ls -l results_hpo_demo

# Commented out IPython magic to ensure Python compatibility.
# %ls -l results_hpo_demo/configs

# Commented out IPython magic to ensure Python compatibility.
# %cat results_hpo_demo/configs/config_1/config.yaml
print()
# %cat results_hpo_demo/configs/config_1/report.yaml

"""The root_directory of the run contains a summary folder with information for the overall HPO run, trajectory of best configs and the best config found so far."""

!cat results_hpo_demo/summary/short.csv

!cat results_hpo_demo/summary/best_config_trajectory.txt

!cat results_hpo_demo/summary/best_config.txt

"""We also store the entire history of the run as a _.csv_ after the optimization budget is exhausted."""

import pandas as pd

df = pd.read_csv("results_hpo_demo/summary/full.csv")
df.head()

# Commented out IPython magic to ensure Python compatibility.
# Load the tensorboard
# %load_ext tensorboard

# %tensorboard --logdir /content/neps_colab_playground/results_hpo_demo

"""For more details on the Tensorboard integration, see documentation [here](https://automl.github.io/neps/latest/reference/analyse/#visualizing-results).

## A slightly more elaborate HPO

Now, we construct a slightly more elaborate search space and perform a longer HPO run.

<!-- *NOTE*: If using a GPU or with time in hand, we recommend `run_pipeline()` or else `run_pipeline_demo()` for shorter, quicker runs. -->

<!-- *NOTE, again*: Using `run_pipeline_demo()` may affect the multi-fidelity runs in this notebook. -->
"""

# Commented out IPython magic to ensure Python compatibility.
# (Optional) Activate live view of Tensorboard output
# NOTE: this will populate once the next run is active and `results_hpo/` is storing data (refresh to see)
# %tensorboard --logdir /content/neps_colab_playground/results_hpo

pipeline_space = dict(
    learning_rate=neps.Float(1e-6, 1e-1, log=True),
    optimizer=neps.Categorical(["sgd", "adamw"]),
    num_neurons=neps.Integer(64, 1024),
)

set_seeds(1)
start = time.time()
neps.run(
    evaluate_pipeline=evaluate_pipeline,  # edit here to change task to optimize
    root_directory="results_hpo",
    pipeline_space=pipeline_space,
    evaluations_to_spend=8,
)

"""Check run status and the best trajectory:"""

!python -m neps.status results_hpo/

"""## Speeding up ...

### ... with parallelization

All code you have seen would already be parallelizable, simply by executing it twice in parallel!

I.e., you can start multiple `neps.run()` from different processes however you like and they will synchronize, as long as they share the same `root_directory=`.

Say you have a script `worker.py` as

```python
# worker.py
neps.run(
    run_pipeline=...,
    pipeline_space=...,
    root_directory="some/path",
    evaluations_to_spend=100,
    max_evaluations_per_run=10,  # Each worker will only run 10 evaluations
)
```

Then, to spawn three parallel workers, you can run
```bash
python worker.py &
python worker.py &
python worker.py &
```

The same magic applies in order to continue HPO on a task: repeating the same call with a higher HPO budget suffices.
"""

neps.run(
    evaluate_pipeline=evaluate_pipeline,
    root_directory="results_hpo",
    pipeline_space=pipeline_space,
    evaluations_to_spend=10  # Increasing the budget to continue run
)

full, summary = neps.status("results_hpo", print_summary=True)

"""### ... with multi-fidelity

The previous setup ran each configuration for the number of `epochs` specified.

However, speedup techniques exploit the notion of _early stopping_ to terminate poor performing configurations by training them for an `epoch` <= `epochs` specified.

Such evaluation of a hyperparameter configuration at a lower epoch than desired is termed as a _cheaper proxy_ or a _lower fidelity_ evaluation.

To allow this, we add `epochs` into our search space and mark it as a _fidelity_.
"""

# Create a new fidelity-enabled search space
pipeline_space_mf = pipeline_space.copy()
pipeline_space_mf["epochs"] = neps.Integer(1, 10, is_fidelity=True)

"""We repeat the same call to `run()`, changing only the output directory."""

set_seeds(1)
start = time.time()
neps.run(
    evaluate_pipeline=evaluate_pipeline,
    root_directory="results_multi_fidelity",
    pipeline_space=pipeline_space_mf,
    fidelities_to_spend=50, # 1/2 the original budget
)

"""Comparing the best observed with the previous HPO run."""

print("Results with multi-fidelity\n")
!python -m neps.status results_multi_fidelity/

print("\n\nCompared to vanilla HPO\n")
!python -m neps.status results_hpo/

"""Our provided code already takes care of model checkpointing."""

!ls results_multi_fidelity/configs/

"""
In the multi-fidelity case, observe the following:"""

# Commented out IPython magic to ensure Python compatibility.
# %cat results_multi_fidelity/configs/config_6_rung_0/config.yaml
print()
# %ls -lh results_multi_fidelity/configs/config_6_rung_0/checkpoint.pth

"""Note the only difference is in `epochs`.




"""

# Commented out IPython magic to ensure Python compatibility.
# %cat results_multi_fidelity/configs/config_6_rung_1/config.yaml
print()
# %ls -lh results_multi_fidelity/configs/config_6_rung_1/checkpoint.pth

"""To obtain the `config_6_rung_1/checkpoint.pth`, the model at `config_6_rung_1/checkpoint.pth` was loaded and continued training.

This is a crucial aspect which allows efficienct HPO in Deep Learning using multi-fidelity optimization.

### ... with priors and multi-fidelity

Here we redefine the search space, by providing defaults to each hyperparameter.

We denote them as `expert priors`, that is, the DL expert seeding the HPO algorithm with their intuition of what is likely a good hyperparameter configuration.

---
"""

# Note the `prior` for each hyperparameter
pipeline_space_expert = dict(
    learning_rate=neps.Float(
        lower=1e-6,
        upper=1e-1,
        log=True,
        prior=0.01,
        prior_confidence="medium"
    ),
    optimizer=neps.Categorical(
        choices=["sgd", "adamw"],
        prior="adamw",
        prior_confidence="high"
    ),
    num_neurons=neps.Integer(
        lower=64,
        upper=1024,
        prior=512,
        prior_confidence="low"
    ),
    epochs=neps.Integer(
        lower=1,
        upper=10,
        is_fidelity=True
    )
)

"""Repeating the same multi-fidelity run command, with a different output directory."""

set_seeds(1)
start = time.time()
neps.run(
    evaluate_pipeline=evaluate_pipeline,
    root_directory="results_multi_fidelity_expert",
    pipeline_space=pipeline_space_expert,
    fidelities_to_spend=50,
)
_ = neps.status("results_multi_fidelity_expert")

"""To compare the results"""

print("Results with expert-priors and multi-fidelity\n")
!python -m neps.status results_multi_fidelity_expert/

print("\n\nResults with multi-fidelity\n")
!python -m neps.status results_multi_fidelity/

"""### Optimizing over multiple-objectives with priors and multi-fidelity

In Deep Learning it is often necessary to optimize over multiple objectives.

So far, we have been running HPO over a single objective: `1 - validation_accuracy`. We now optimize over 2 objectives by adding the `cost` objective.

Furthermore, we now define priors over each of the 2 objectives.

We use the same evaluation pipeline as seen previously and merge the existing objective with the cost to create a multi-objective function
"""

# Augmenting the evaluation pipeline with a cost objective
def mo_evaluate_pipeline(
    pipeline_directory,  # For saving checkpoints
    previous_pipeline_directory,  # For loading checkpoints
    **hyperparameters,  # Determined by HPO algorithms and passed by NePS
):
    result = training_pipeline(
        **hyperparameters,
        out_dir=pipeline_directory,
        load_dir=previous_pipeline_directory,
        # misc settings
        batch_size=512,
        log_neps_tensorboard=True,
        verbose=False,
        allow_checkpointing=True,
        use_for_demo=True  # toggle as desired
    )
    m_objective = [result["objective_to_minimize"], result["cost"]]
    result["objective_to_minimize"] = m_objective
    return result

"""We inject centers for Gaussian Priors over the two objectives, in the multi-fidelity pipeline space seen before."""

prior_centers = {
    "val_error": {
        "learning_rate": 0.01,
        "optimizer": "adamw",
        "num_neurons": 512,
    },
    "cost": {
        "learning_rate": 0.3,
        "optimizer": "adamw",
        "num_neurons": 128,
    }
}

"""Running multi-objective HPO with priors over multiple objectives using PriMO"""

set_seeds(1)
start = time.time()
neps.run(
    evaluate_pipeline=mo_evaluate_pipeline,  # edit here to change task to optimize
    root_directory="results_mohpo_priors",
    overwrite_root_directory=True,
    pipeline_space=pipeline_space_mf,
    fidelities_to_spend=100,
    optimizer=("primo", {"prior_centers": prior_centers})
)

"""The `objective_to_minimize` in case of multi-objective HPO is a list of floats, as seen below"""

# Commented out IPython magic to ensure Python compatibility.
# %cat results_mohpo_priors/configs/config_2_rung_2/report.yaml

"""Plotting a Pareto Front based on the multi-objective priors-based HPO run"""

from PIL import Image
!python plot.py --root_directory results_mohpo_priors --do pareto_front --filename pareto_front.png --objectives "1 - validation_accuracy" "cost"
img = Image.open("results_mohpo_priors/pareto_front.png")
img_resized = img.resize((800, 500))
display(img_resized)

"""## What's next?

Dive deeper with
* [Examples](https://github.com/automl/neps/tree/master/neps_examples)
* [Documentation](https://automl.github.io/neps/latest/)
* [NePS repository](https://github.com/automl/neps)
* [Deep Learning 2.0](https://www.automl.org/deep-learning-2-0-extending-the-power-of-deep-learning-to-the-meta-level/)
"""