# Pipeline_space including priors and fidelity
learning_rate:
  lower: 1e-5
  upper: 1e-1
  log: true  # Log scale for learning rate
  prior: 1e-2
  prior_confidence: "medium"
epochs:
  lower: 5
  upper: 20
  is_fidelity: true
dropout_rate:
  lower: 0.1
  upper: 0.5
  prior: 0.2
  prior_confidence: "high"
optimizer:
  choices: [adam, sgd, adamw]
  prior: adam
  # if prior confidence is not defined it gets its default 'low'
batch_size: 64
