class Filenamings:
    """
    Filenamings provides a centralized approach to manage and keep track of the
    various files generated by NePS in the user's directory. As the number of
    generated files increases, maintaining a clear understanding of file names
    and their locations becomes crucial.

    Contributors are encouraged to utilize this class to centralize information
    related to file names, locations, and functionalities, making it easier to
    manage and modify file-related aspects in the future.

    It is highly recommended to adhere to a naming convention where the variable
    names reflect the location, the type (directory or file), and purpose of the
    associated file or directory.

    General:
    - location_type_purpose

    Example:
    - root_directory_results (str): Represents the name of the result directory
        located in the root directory.
    - root_file_locker (str): Represents the name of the locker file located in
        the root directory.
    """

    root_directory_results = "results"
    root_directory_summary_csv = "summary_csv"
    root_directory_summary_tblogger = "summary_tblogger"
    root_file_locker = ".decision_lock"
    root_file_all_losses_w_configs = "all_losses_and_configs.txt"
    root_file_best_loss_traj = "best_loss_trajectory.txt"
    root_file_config_w_best_loss_traj = "best_loss_with_config_trajectory.txt"
    root_file_optimizer_state = ".optimizer_state.yaml"
    root_file_optimizer_info = ".optimizer_info.yaml"

    summary_file_locker = ".summary_lock"
    summary_file_config_result = "config_data.csv"
    summary_file_run_status = "run_status.csv"

    config_directory_tblogger = "tbevents"
    config_file_locker = ".config_lock"
    config_file_config_details = "config"
    config_file_metadata_details = "metadata"
    config_file_result_details = "result"
    config_file_id_previous_config = "previous_config.id"
